const countries = {
    "USD": "US",
    "GBP": "GB",
    "EUR": "EU",
    "JPY": "JP",
    "AUD": "AU",
    "CAD": "CA",
    "CHF": "CH",
    "CNY": "CN",
    "INR": "IN",
    "NZD": "NZ",
    "BRL": "BR",
    "ZAR": "ZA",
    "RUB": "RU",
    "KRW": "KR",
    "SGD": "SG",
    "MXN": "MX",
    "AED": "AE",
    "SAR": "SA",
    "HKD": "HK",
    "THB": "TH"
};